"""Add Poster Entity

Revision ID: d5a7f128c903
Revises: 79f5e743ff9c
Create Date: 2024-12-18 21:23:36.638182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a7f128c903'
down_revision: Union[str, None] = '79f5e743ff9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'poster_id')
    # ### end Alembic commands ###
